package codegen

import (
	"fmt"
	"strings"

	"github.com/derekmartinsdev/sieve/ast"
	"github.com/derekmartinsdev/sieve/pipeline"
)

type Generator struct {
	imports    map[string]bool
	variables  []string
	indent     int
}

func New() *Generator {
	return &Generator{
		imports:   make(map[string]bool),
		variables: []string{},
	}
}

func (g *Generator) Generate(prog *ast.Program) string {
	g.imports["from pyspark.sql import SparkSession, functions as F"] = true
	g.imports["from pyspark.sql.types import *"] = true

	var out strings.Builder
	out.WriteString(g.generateHeader())
	out.WriteString("\n")

	for _, stmt := range prog.Statements {
		switch s := stmt.(type) {
		case *ast.SourceStatement:
			out.WriteString(g.generateSource(s))
		case *ast.AssignmentStatement:
			out.WriteString(g.generateAssignment(s))
		}
	}

	out.WriteString("\n")
	out.WriteString("spark.stop()\n")

	return out.String()
}

func (g *Generator) generateHeader() string {
	var out strings.Builder
	out.WriteString("# Auto-generated by sieve transpiler\n")
	out.WriteString("# Original DSL -> PySpark\n\n")

	for imp := range g.imports {
		out.WriteString(imp + "\n")
	}

	out.WriteString("\nspark = SparkSession.builder.appName(\"sieve\").getOrCreate()\n\n")
	return out.String()
}

func (g *Generator) generateSource(s *ast.SourceStatement) string {
	var out strings.Builder
	varName := g.varName(s.Name)

	if s.S3 != nil {
		out.WriteString(fmt.Sprintf("# Source: %s\n", s.Name))
		out.WriteString(fmt.Sprintf("%s = spark.read.format(\"%s\")", varName, s.S3.Format))
		if s.S3.Bucket != "" {
			out.WriteString(fmt.Sprintf(".option(\"header\", \"true\")"))
		}
		out.WriteString(fmt.Sprintf(".load(\"s3a://%s/%s\")\n", s.S3.Bucket, s.S3.Prefix))
		out.WriteString("\n")

		for _, ext := range s.Extracts {
			out.WriteString(g.generateExtract(varName, ext))
		}
	} else {
		out.WriteString(fmt.Sprintf("%s = %s\n", varName, g.varName(s.Name)))
	}

	return out.String()
}

func (g *Generator) generateExtract(dfVar string, ext ast.ExtractStatement) string {
	var out strings.Builder

	if ext.Path != "" {
		parsedVar := dfVar + "_parsed"
		switch ext.JsonType {
		case "select":
			out.WriteString(fmt.Sprintf("# Parse JSON fields from %s.%s\n", dfVar, ext.Path))
			out.WriteString(fmt.Sprintf("%s = %s \\\n", parsedVar, dfVar))

			for i, field := range ext.Fields {
				colName := field.Alias
				if colName == "" {
					colName = field.SourcePath
				}

				jsonPath := strings.ReplaceAll(field.SourcePath, ".", ".")

				out.WriteString(fmt.Sprintf("    .withColumn(\"%s\", F.col(\"%s.%s\"))\n", colName, ext.Path, jsonPath))
				_ = i
			}

			out.WriteString(fmt.Sprintf("    .drop(\"%s\")\n", ext.Path))
			out.WriteString("\n")

		case "explode":
			out.WriteString(fmt.Sprintf("# Explode array from %s.%s\n", dfVar, ext.Path))
			if ext.IsArray {
				out.WriteString(fmt.Sprintf("%s = %s \\\n", parsedVar, dfVar))
				out.WriteString(fmt.Sprintf("    .withColumn(\"%s\", F.explode(\"%s\"))\n", ext.Path, ext.Path))

				for _, field := range ext.Fields {
					out.WriteString(fmt.Sprintf("    .select(\"*\", \"%s.%s\")\n", ext.Path, field.SourcePath))
				}
				out.WriteString("\n")
			}
		}

		dfVar = parsedVar
	}

	return out.String()
}

func (g *Generator) generateAssignment(s *ast.AssignmentStatement) string {
	var out strings.Builder
	varName := g.varName(s.Name)

	if join, ok := s.Value.(*ast.JoinStatement); ok {
		out.WriteString(fmt.Sprintf("# Join: %s /\\ %s\n", join.Left, join.Right))

		leftVar := g.varName(join.Left)
		rightVar := g.varName(join.Right)

		joinType := "inner"
		if join.JoinType == "left" {
			joinType = "left"
		}

		condition := g.parseJoinCondition(join.Condition, join.Left, join.Right)

		out.WriteString(fmt.Sprintf("%s = %s.join(%s, %s, \"%s\")\n",
			varName, leftVar, rightVar, condition, joinType))
		out.WriteString("\n")
	}

	return out.String()
}

func (g *Generator) varName(name string) string {
	name = strings.ReplaceAll(name, ".", "_")
	name = strings.ReplaceAll(name, "-", "_")
	return "df_" + name
}

func (g *Generator) typeCast(colName string, ft ast.FieldType) string {
	sparkType := g.toSparkType(ft)
	if sparkType == "" {
		return ""
	}
	return fmt.Sprintf(".withColumn(\"%s\", F.col(\"%s\").cast(\"%s\"))", colName, colName, sparkType)
}

func (g *Generator) toSparkType(ft ast.FieldType) string {
	switch ft.BaseType {
	case "string":
		return "StringType()"
	case "bigint":
		return "LongType()"
	case "int":
		return "IntegerType()"
	case "decimal":
		if len(ft.Params) >= 2 {
			return fmt.Sprintf("DecimalType(%s, %s)", ft.Params[0], ft.Params[1])
		}
		return "DecimalType(18, 2)"
	case "date":
		return "DateType()"
	case "double":
		return "DoubleType()"
	case "float":
		return "FloatType()"
	default:
		return ""
	}
}

func (g *Generator) parseJoinCondition(cond string, leftTable string, rightTable string) string {
	cond = strings.ReplaceAll(cond, leftTable+".", "F.col(\""+leftTable+".")
	cond = strings.ReplaceAll(cond, rightTable+".", "F.col(\""+rightTable+".")
	cond = strings.ReplaceAll(cond, "= ", "\") = ")

	return cond
}

func (g *Generator) GenerateSelect(dfVar string, fields []ast.SelectField) string {
	var out strings.Builder
	out.WriteString(fmt.Sprintf("%s = %s.select(\n", dfVar, dfVar))

	for i, field := range fields {
		colExpr := field.Source
		if field.Path != "" {
			colExpr = field.Source + "." + field.Path
		} else {
			colExpr = field.Alias
		}

		alias := field.Alias
		if alias == "" {
			alias = colExpr
		}

		if colExpr != alias {
			out.WriteString(fmt.Sprintf("    F.col(\"%s\").alias(\"%s\")", colExpr, alias))
		} else {
			out.WriteString(fmt.Sprintf("    F.col(\"%s\")", colExpr))
		}

		if i < len(fields)-1 {
			out.WriteString(",")
		}
		out.WriteString("\n")
	}

	out.WriteString(")\n")
	return out.String()
}

func (g *Generator) GenerateOutput(dfVar string, output *ast.OutputTarget) string {
	if output == nil || output.S3 == nil {
		return ""
	}

	var out strings.Builder
	out.WriteString(fmt.Sprintf("# Write to S3\n"))
	out.WriteString(fmt.Sprintf("%s.write \\\n", dfVar))
	out.WriteString(fmt.Sprintf("    .format(\"%s\") \\\n", output.S3.Format))
	out.WriteString(fmt.Sprintf("    .mode(\"%s\") \\\n", output.Mode))

	if len(output.PartitionBy) > 0 {
		out.WriteString(fmt.Sprintf("    .partitionBy(\"%s\") \\\n", strings.Join(output.PartitionBy, "\", \"")))
	}

	out.WriteString(fmt.Sprintf("    .save(\"s3a://%s/%s\")\n", output.S3.Bucket, output.S3.Prefix))
	out.WriteString("\n")

	return out.String()
}

func (g *Generator) GeneratePipeline(dfVar string, fieldName string, stages []ast.PipelineStage) string {
	var out strings.Builder
	p := &pipeline.Pipeline{}

	for _, stage := range stages {
		p.Operators = append(p.Operators, pipeline.Operator{
			Name: stage.Name,
			Args: stage.Args,
		})
	}

	colExpr := fmt.Sprintf("F.col(\"%s\")", fieldName)
	result := p.GeneratePySpark(colExpr)

	out.WriteString(fmt.Sprintf("%s = %s.withColumn(\"%s\", %s)\n",
		dfVar, dfVar, fieldName, result))

	return out.String()
}